[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "convert-slides"
description = "Tool to translate slides using OpenAI"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "openai==1.26",
]